### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by msmyers** [typhonjs-node-esdoc/typhonjs-node-esdoc#1]
I have spent a great deal of my time forking esdoc and sifting through the numerous errors.

Perhaps 4 solid days of reverse engineering (over the past few months).

I came across your fork, and it worked first try.

Thanks.

**Comment by typhonrt** [comment]
Thanks for the nod.  As mentioned in the esdoc repo issue for this fork my hope is that the official ESDoc `v1.0.0` release will satisfy those that have been using my fork in the meantime. 

---

(Copied from my response on the esdoc repo for reference) It does look like @h13i32maru is mostly done supporting Babylon with ESDoc, but I haven't tested it myself. You might try and link the master branch of ESDoc via:
"esdoc": "git+https://git@github.com/esdoc/esdoc.git"
and see if it can parse your project. Providing a new issue with an error report for any inconsistency between my fork and the master branch of ESDoc will really help in the next official release of ESDoc.

As things go if you link to the master branch of ESDoc you'll have to manually transpile the source code. Adding a NPM script in package.json such as "build-esdoc": "babel ./node_modules/esdoc/src -d ./node_modules/esdoc/out/src should do.
